[project]
name = "dashblock-reborn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fabric>=3.2.2",
    "litestar>=2.17.0",
    "uvicorn>=0.35.0",
]
